id = "ow-lsp-colors"
name = "OW LSP Colors"
description = "Highlight colors inline in your editor. Fork of color-highlight with extended language support."
version = "0.3.0"
schema_version = 1
authors = ["Benjamin Schulz <benjamin@omniwerk.de>"]
repository = "https://github.com/benjaminschulz/ow-lsp-colors"

[language_servers.color-lsp]
name = "ColorLSP Server"
languages = [
    "HTML",
    "JSON",
    "JSONC",
    "JSON5",
    "Tera",
    "Tera (HTML)",
    "Tera (CSS)",
    "Tera (JSON)",
    "Tera (YAML)",
    "Tera (TOML)",
    "ERB",
    "JavaScript",
    "TypeScript",
    "CSS",
    "JSX",
    "TSX",
    "Vue.js",
    "YAML",
    "TOML",
    "XML",
    "Rust",
    "Ruby",
    "Python",
    "Go",
    "PHP",
    "Markdown",
    "C",
    "C++",
    "C#",
    "Java",
    "Kotlin",
    "Swift",
    "Dart",
    "Elixir",
    "Elm",
    "Haskell",
    "Lua",
    "Scala",
    "Zig",
    "Bash",
    "Fish",
    "Shell Script",
    "SQL",
    "GraphQL",
    "Svelte",
    "Astro",
    "SCSS",
    "Less",
    "Tailwind CSS",
    "Dockerfile",
    "Makefile",
    "Nix",
    "Terraform",
    "LaTeX",
    "Typst",
    "AsciiDoc",
    "Clojure",
    "Erlang",
    "Gleam",
    "OCaml",
    "Racket",
    "Scheme",
    "GDScript",
    "GLSL",
    "WGSL",
    "INI",
    "Env",
    "Prisma",
    "Proto",
]
code_action_kinds = []
